"""
Renders FlowTracer entry points and DocCache summaries to markdown.

Produces two documents:
  FLOWS.md   — all entry points grouped by kind, with call chains,
               decoupled flows, and any cached LLM summary.
  SUMMARY.md — all cached function docs grouped by source file,
               updated incrementally as generate / diff-test runs.
"""

from __future__ import annotations

import re
from collections import defaultdict
from datetime import date
from typing import Dict, List, Optional

from codecoverage.core.doc_cache import DocCache
from codecoverage.web.flow_tracer import EntryPoint


_KIND_ORDER = ["http", "task", "signal", "command"]
_KIND_LABELS: Dict[str, str] = {
    "http":    "HTTP Endpoints",
    "task":    "Background Tasks",
    "signal":  "Signal Handlers",
    "command": "Management Commands",
}

_CALL_CHAIN_LIMIT = 7


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def render_flows_markdown(
    entry_points: List[EntryPoint],
    project_name: str,
    doc_cache: Optional[DocCache] = None,
) -> str:
    today = date.today().isoformat()
    lines: List[str] = []

    lines += [
        f"# {project_name} — Flow Documentation",
        "",
        f"Generated by codecoverage on {today}.",
        "",
    ]

    by_kind: Dict[str, List[EntryPoint]] = defaultdict(list)
    for ep in entry_points:
        by_kind[ep.kind].append(ep)

    total = len(entry_points)
    counts_line = " · ".join(
        f"{len(by_kind[k])} {_KIND_LABELS[k]}"
        for k in _KIND_ORDER
        if by_kind.get(k)
    )
    lines += [f"**{total} entry points** — {counts_line}", ""]

    # Category-level TOC
    lines.append("## Contents")
    lines.append("")
    for kind in _KIND_ORDER:
        eps = by_kind.get(kind, [])
        if not eps:
            continue
        label = _KIND_LABELS[kind]
        anchor = _to_anchor(f"{label} ({len(eps)})")
        lines.append(f"- [{label} ({len(eps)})](#{anchor})")
    lines += ["", "---", ""]

    for kind in _KIND_ORDER:
        eps = by_kind.get(kind, [])
        if not eps:
            continue
        label = _KIND_LABELS[kind]
        lines += [f"## {label} ({len(eps)})", ""]
        for ep in eps:
            lines += _render_entry_point(ep, doc_cache)

    return "\n".join(lines)


def render_summary_markdown(
    doc_cache: DocCache,
    project_name: str,
    test_refs_map: Optional[Dict[str, list]] = None,
) -> str:
    today = date.today().isoformat()
    lines: List[str] = []

    lines += [
        f"# {project_name} — Function Summaries",
        "",
        f"Generated by codecoverage on {today}.",
        "",
    ]

    by_file: Dict[str, Dict[str, dict]] = defaultdict(dict)
    for key, entry in doc_cache._data.items():
        if "::" not in key:
            continue
        rel_file, func_name = key.split("::", 1)
        by_file[rel_file][func_name] = entry

    if not by_file:
        lines += [
            "*No cached function documentation yet.*",
            "*Run `codecoverage generate` or `codecoverage diff-test` to populate.*",
        ]
        return "\n".join(lines)

    lines += [f"**{len(doc_cache)} function(s) documented**", ""]

    # File-level TOC
    lines.append("## Contents")
    lines.append("")
    for rel_file in sorted(by_file.keys()):
        filename = rel_file.split("/")[-1]
        anchor = _to_anchor(f"`{rel_file}`")
        func_count = len(by_file[rel_file])
        lines.append(f"- [`{filename}`](#{anchor}) — {func_count} function(s)")
    lines += ["", "---", ""]

    for rel_file in sorted(by_file.keys()):
        funcs = by_file[rel_file]
        lines += [f"## `{rel_file}`", ""]
        for func_name in sorted(funcs.keys()):
            entry = funcs[func_name]
            refs = (test_refs_map or {}).get(f"{rel_file}::{func_name}", [])
            lines += _render_doc_entry(func_name, entry, refs)

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Private helpers
# ---------------------------------------------------------------------------

def _render_entry_point(
    ep: EntryPoint,
    doc_cache: Optional[DocCache],
) -> List[str]:
    lines: List[str] = []

    lines.append(f"### {ep.label}")
    lines.append("")

    if ep.url_path:
        methods = " / ".join(ep.http_methods) if ep.http_methods else "GET"
        lines.append(f"**`{methods} {ep.url_path}`**")
    lines.append(f"`{ep.file}`")
    lines.append("")

    # LLM summary or first line of static docstring
    llm_summary = _resolve_summary(ep, doc_cache)
    if llm_summary:
        lines.append(f"> {llm_summary}")
        lines.append("")
    elif ep.description:
        first_line = ep.description.strip().splitlines()[0][:120]
        lines.append(f"> {first_line}")
        lines.append("")

    # Call chain — capped at _CALL_CHAIN_LIMIT
    if ep.call_chain:
        total_steps = len(ep.call_chain)
        shown = ep.call_chain[:_CALL_CHAIN_LIMIT]
        lines.append("**Call chain**")
        lines.append("")
        for i, step in enumerate(shown, 1):
            if hasattr(step, "alternatives"):
                # FlowFork — one of several possible implementations
                alts = " / ".join(f"`{s.name}`" for s in step.alternatives)
                lines.append(f"{i}. {alts} *(fork)*")
            else:
                lines.append(f"{i}. `{step.name}` — `{step.file}`")
        if total_steps > _CALL_CHAIN_LIMIT:
            lines.append(
                f"   *...and {total_steps - _CALL_CHAIN_LIMIT} more internal calls*"
            )
        lines.append("")

    # Decoupled flows
    if ep.decoupled_flows:
        lines.append("**Decoupled flows**")
        lines.append("")
        grouped: Dict[str, list] = defaultdict(list)
        for df in ep.decoupled_flows:
            grouped[df.decorator_name].append(df)
        for dec_name, flows in grouped.items():
            lines.append(f"*@{dec_name}*")
            for df in flows:
                lines.append(
                    f"- `{df.decorator_repr}` → `{df.function_name}` (`{df.file}`)"
                )
            lines.append("")

    lines += ["---", ""]
    return lines


def _render_doc_entry(func_name: str, entry: dict, test_refs: list = None) -> List[str]:
    lines: List[str] = []

    lines.append(f"### `{func_name}`")
    lines.append("")

    if entry.get("summary"):
        lines.append(entry["summary"])
        lines.append("")

    # Side effects — handle list (old schema) and string (new schema)
    side_effects = entry.get("side_effects")
    if side_effects:
        if isinstance(side_effects, list):
            se_line = " · ".join(s for s in side_effects if s)
            if se_line:
                lines.append(f"> **Side effects:** {se_line}")
                lines.append("")
        elif isinstance(side_effects, str) and side_effects.strip().lower() not in ("", "null", "none"):
            lines.append(f"> **Side effects:** {side_effects.strip()}")
            lines.append("")

    # Note (new schema only)
    note = entry.get("note")
    if note and isinstance(note, str) and note.strip().lower() not in ("", "null", "none"):
        lines.append(f"> **Note:** {note.strip()}")
        lines.append("")

    if test_refs:
        parts = []
        for ref in test_refs:
            tests_str = ", ".join(f"`{t}`" for t in ref["tests"])
            parts.append(f"`{ref['file']}` — {tests_str}")
        lines.append("**Tests:** " + " · ".join(parts))
        lines.append("")

    if entry.get("updated_at"):
        lines.append(f"*{entry['updated_at'][:10]}*")
        lines.append("")

    lines += ["---", ""]
    return lines


def _resolve_summary(
    ep: EntryPoint,
    doc_cache: Optional[DocCache],
) -> Optional[str]:
    if doc_cache is None:
        return None

    s = doc_cache.get_summary(ep.file, ep.label)
    if s:
        return s

    for step in ep.call_chain:
        if not hasattr(step, "file"):  # skip FlowFork entries
            continue
        if step.file == ep.file:
            s = doc_cache.get_summary(step.file, step.name)
            if s:
                return s

    return None


def _to_anchor(text: str) -> str:
    """Convert a heading string to a GitHub-style markdown anchor."""
    text = text.lower()
    text = re.sub(r"[^\w\s-]", "", text)
    text = re.sub(r"\s+", "-", text.strip())
    return text
