"""
OpenAPI 3.0 schema generator from a parsed Codebase.

Detects Django/DRF projects and maps URL patterns to view classes.
For all projects, generates components from classes and tags from modules.
Adds x-decoupled-flows as a top-level extension.
"""

import ast
import re
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

from codecoverage.core.codebase import ClassInfo, Codebase, FileInfo, FunctionInfo

_HTTP_METHODS = {"get", "post", "put", "patch", "delete", "head", "options", "trace"}
_NOISE_DECORATORS = {
    "staticmethod", "classmethod", "property", "override",
    "abstractmethod", "cached_property",
}


# ---------------------------------------------------------------------------
# Public entry point
# ---------------------------------------------------------------------------

def generate_openapi_spec(
    codebase: Codebase,
    project_root: Path,
    entry_points: Optional[List[Any]] = None,
    doc_cache: Optional[Any] = None,
) -> Dict[str, Any]:
    """
    Generate an OpenAPI 3.0 spec dict from a parsed Codebase.

    Args:
        codebase:      Parsed codebase object.
        project_root:  Absolute path to the project root (used for display names).
        entry_points:  Pre-computed entry points from FlowTracer. If None, they are
                       computed internally (pass them in to avoid a double trace when
                       the caller already has them).
        doc_cache:     Optional DocCache instance for LLM-enriched descriptions.

    Returns:
        OpenAPI 3.0 spec as a plain dict (JSON-serialisable).
    """
    from codecoverage.web.flow_tracer import FlowTracer

    title = project_root.name
    is_django = _is_django_project(codebase)

    # Use caller-supplied entry points to avoid re-tracing the codebase
    if entry_points is None:
        tracer = FlowTracer(codebase, project_root)
        entry_points = tracer.detect_all_entry_points()

    # Index HTTP entry points by label for fast lookup during path building
    http_ep_by_label: Dict[str, Any] = {
        ep.label: ep for ep in entry_points if ep.kind == "http"
    }

    paths: Dict[str, Any] = {}
    tags: List[Dict[str, str]] = []

    # Build per-module tags
    for file_info in sorted(codebase.files.values(), key=lambda f: f.module_name):
        tag: Dict[str, str] = {"name": file_info.module_name}
        if file_info.docstring:
            tag["description"] = file_info.docstring
        tags.append(tag)

    # Django: extract URL → view → HTTP method mappings, enriched with flow data
    if is_django:
        paths = _extract_django_paths(codebase, project_root, http_ep_by_label, doc_cache)

    # Components from all classes
    components = _build_components(codebase)

    spec: Dict[str, Any] = {
        "openapi": "3.0.3",
        "info": {
            "title": title,
            "version": "0.0.0",
            "description": (
                f"Auto-generated by codecoverage from `{project_root}`.\n\n"
                "This spec reflects the parsed codebase — not a running API.\n\n"
                "**Browse the full flow documentation at `/flows`.**"
            ),
        },
        "tags": tags,
        "paths": paths,
        "components": components,
        "x-decoupled-flows": _build_decoupled_flows(codebase, project_root),
    }

    return spec


# ---------------------------------------------------------------------------
# Django detection
# ---------------------------------------------------------------------------

def _is_django_project(codebase: Codebase) -> bool:
    """Return True if any file imports from django.conf.urls or django.urls."""
    for file_info in codebase.files.values():
        for imp in file_info.imports:
            if "django.conf.urls" in imp or "django.urls" in imp:
                return True
    return False


# ---------------------------------------------------------------------------
# Django URL parsing
# ---------------------------------------------------------------------------

def _extract_django_paths(
    codebase: Codebase,
    project_root: Path,
    http_ep_by_label: Optional[Dict[str, Any]] = None,
    doc_cache: Optional[Any] = None,
) -> Dict[str, Any]:
    """
    Parse all urls.py files and return an OpenAPI paths object.

    Each URL pattern is mapped to an OpenAPI path item with one or more
    HTTP method operations derived from the view class methods.
    """
    paths: Dict[str, Any] = {}

    for file_info in codebase.files.values():
        if not file_info.path.name == "urls.py":
            continue

        try:
            source = file_info.path.read_text(encoding="utf-8")
        except OSError:
            continue

        try:
            tree = ast.parse(source)
        except SyntaxError:
            continue

        for node in ast.walk(tree):
            if not (
                isinstance(node, ast.Assign)
                and len(node.targets) == 1
                and isinstance(node.targets[0], ast.Name)
                and node.targets[0].id == "urlpatterns"
            ):
                continue

            if not isinstance(node.value, (ast.List, ast.Tuple)):
                continue

            for elt in node.value.elts:
                item = _parse_url_pattern(
                    elt, codebase, file_info,
                    http_ep_by_label=http_ep_by_label or {},
                    doc_cache=doc_cache,
                )
                if item is None:
                    continue
                openapi_path, path_item = item
                if openapi_path in paths:
                    paths[openapi_path].update(path_item)
                else:
                    paths[openapi_path] = path_item

    return paths


def _parse_url_pattern(
    node: ast.expr,
    codebase: Codebase,
    urls_file: FileInfo,
    http_ep_by_label: Optional[Dict[str, Any]] = None,
    doc_cache: Optional[Any] = None,
) -> Optional[Tuple[str, Dict[str, Any]]]:
    """
    Parse a single urlpatterns element.

    Handles:
    - url(pattern, view.as_view(), name='...')
    - re_path(pattern, view.as_view(), name='...')
    - path(pattern, view.as_view(), name='...')

    Returns (openapi_path_string, path_item_dict) or None.
    """
    if not isinstance(node, ast.Call):
        return None

    func_name = _call_func_name(node)
    if func_name not in ("url", "re_path", "path", "include"):
        return None
    if func_name == "include":
        return None

    if len(node.args) < 2:
        return None

    raw_pattern = _eval_str(node.args[0])
    if raw_pattern is None:
        return None

    view_node = node.args[1]
    view_class_name = _extract_view_class_name(view_node)
    if view_class_name is None:
        return None

    openapi_path = _regex_to_openapi_path(raw_pattern)

    # URL name (keyword arg)
    url_name: Optional[str] = None
    for kw in node.keywords:
        if kw.arg == "name":
            url_name = _eval_str(kw.value)

    # Extract path parameters from the openapi_path
    path_params = re.findall(r"\{(\w+)\}", openapi_path)

    # Look up view class in codebase
    class_list = codebase.classes_by_name.get(view_class_name, [])
    class_info = class_list[0] if class_list else None

    ep = (http_ep_by_label or {}).get(view_class_name)

    path_item = _build_path_item(
        view_class_name=view_class_name,
        class_info=class_info,
        url_name=url_name,
        path_params=path_params,
        openapi_path=openapi_path,
        urls_file=urls_file,
        entry_point=ep,
        doc_cache=doc_cache,
    )
    return openapi_path, path_item


def _build_path_item(
    view_class_name: str,
    class_info: Optional[ClassInfo],
    url_name: Optional[str],
    path_params: List[str],
    openapi_path: str,
    urls_file: FileInfo,
    entry_point: Optional[Any] = None,
    doc_cache: Optional[Any] = None,
) -> Dict[str, Any]:
    """Build an OpenAPI path item dict for a single URL."""
    path_item: Dict[str, Any] = {}

    if path_params:
        path_item["parameters"] = [
            {
                "name": p,
                "in": "path",
                "required": True,
                "schema": {"type": "string"},
            }
            for p in path_params
        ]

    # Resolve LLM summary for this view class (if cached).
    # Try direct class-name match first, then walk the call chain for same-file matches.
    llm_summary: Optional[str] = None
    if doc_cache is not None and entry_point is not None:
        ep_file = getattr(entry_point, "file", "")
        llm_summary = doc_cache.get_summary(ep_file, view_class_name)
        if not llm_summary:
            for step in getattr(entry_point, "call_chain", []):
                if step.file == ep_file:
                    llm_summary = doc_cache.get_summary(step.file, step.name)
                    if llm_summary:
                        break

    if class_info is None:
        path_item["get"] = {
            "summary": url_name or openapi_path,
            "operationId": _make_operation_id("get", view_class_name, url_name),
            "tags": [urls_file.module_name],
            "responses": {"200": {"description": "OK"}},
        }
        return path_item

    found_methods = False
    for method in class_info.methods:
        method_name = method.name.lower()
        if method_name not in _HTTP_METHODS:
            continue
        found_methods = True
        operation = _build_operation(
            http_method=method_name,
            view_class_name=view_class_name,
            method_info=method,
            class_info=class_info,
            url_name=url_name,
            urls_module=urls_file.module_name,
            entry_point=entry_point,
            llm_summary=llm_summary,
        )
        path_item[method_name] = operation

    if not found_methods:
        desc = _build_flow_description(class_info.docstring or "", entry_point, llm_summary)
        path_item["get"] = {
            "summary": url_name or view_class_name,
            "operationId": _make_operation_id("get", view_class_name, url_name),
            "description": desc,
            "tags": [urls_file.module_name],
            "responses": {"200": {"description": "OK"}},
        }

    return path_item


def _build_operation(
    http_method: str,
    view_class_name: str,
    method_info: FunctionInfo,
    class_info: ClassInfo,
    url_name: Optional[str],
    urls_module: str,
    entry_point: Optional[Any] = None,
    llm_summary: Optional[str] = None,
) -> Dict[str, Any]:
    """Build an OpenAPI operation object from a view method."""
    operation: Dict[str, Any] = {
        "operationId": _make_operation_id(http_method, view_class_name, url_name),
        "summary": url_name or f"{view_class_name}.{method_info.name}",
        "tags": [urls_module],
        "responses": {"200": {"description": "OK"}, "400": {"description": "Bad Request"}},
    }

    # Build description: LLM summary (if cached) + docstring + call chain + decoupled flows
    operation["description"] = _build_flow_description(
        method_info.docstring or class_info.docstring or "",
        entry_point,
        llm_summary=llm_summary,
    )

    serializer_class = _find_class_variable(class_info, "serializer_class")
    if serializer_class and http_method in ("post", "put", "patch"):
        operation["requestBody"] = {
            "content": {
                "application/json": {
                    "schema": {"$ref": f"#/components/schemas/{serializer_class}"}
                }
            }
        }

    return operation


def _build_flow_description(
    docstring: str,
    entry_point: Optional[Any],
    llm_summary: Optional[str] = None,
) -> str:
    """
    Compose a rich markdown description.

    Priority: LLM summary (if cached) → docstring → call chain → decoupled flows.
    If no entry_point is provided, returns the LLM summary or docstring as-is.
    """
    parts: List[str] = []

    if llm_summary:
        parts.append(f"**{llm_summary}**")

    if docstring:
        parts.append(docstring)

    if entry_point is None:
        return "\n\n".join(parts)

    # Call chain section
    chain = getattr(entry_point, "call_chain", [])
    if chain:
        parts.append("---\n**Call chain** *(static analysis — depth 4)*")
        for step in chain:
            doc_hint = f" — {step.docstring[:80]}" if step.docstring else ""
            parts.append(f"- `{step.signature}` *({step.file})*{doc_hint}")

    # Decoupled flows section
    flows = getattr(entry_point, "decoupled_flows", [])
    if flows:
        parts.append("---\n**Decoupled flows in this execution path**")
        # Group by decorator name
        by_dec: Dict[str, list] = {}
        for flow in flows:
            by_dec.setdefault(flow.decorator_name, []).append(flow)
        for dec_name, entries in sorted(by_dec.items()):
            parts.append(f"\n*{dec_name}*")
            for e in entries:
                doc_hint = f" — {e.docstring[:80]}" if e.docstring else ""
                parts.append(f"- `{e.decorator_repr}` → `{e.function_name}` *({e.file})*{doc_hint}")

    return "\n\n".join(parts)


# ---------------------------------------------------------------------------
# Components from all classes
# ---------------------------------------------------------------------------

def _build_components(codebase: Codebase) -> Dict[str, Any]:
    """Build OpenAPI components/schemas from all parsed classes."""
    schemas: Dict[str, Any] = {}

    for file_info in codebase.files.values():
        for cls in file_info.classes:
            # Sanitise name for OpenAPI (must be alphanumeric + _)
            schema_name = re.sub(r"[^A-Za-z0-9_]", "_", cls.name)
            schema: Dict[str, Any] = {"type": "object"}
            if cls.docstring:
                schema["description"] = cls.docstring
            if cls.bases:
                schema["x-bases"] = cls.bases
            if cls.class_variables:
                schema["properties"] = {
                    v: {"type": "string"} for v in cls.class_variables
                }
            if cls.methods:
                schema["x-methods"] = [
                    {
                        "name": m.name,
                        "signature": m.signature,
                        "description": m.docstring or "",
                    }
                    for m in cls.methods
                ]
            schemas[schema_name] = schema

    return {"schemas": schemas}


# ---------------------------------------------------------------------------
# Decoupled flows extension
# ---------------------------------------------------------------------------

def _build_decoupled_flows(
    codebase: Codebase, project_root: Path
) -> Dict[str, Any]:
    """
    Build the x-decoupled-flows extension dict.

    Structure:
      { "relative/path/to/file.py": { "ClassName": { "decorator": [...] } } }
    """
    result: Dict[str, Any] = {}

    for file_info in codebase.files.values():
        file_flows: Dict[str, Any] = {}

        # Class methods
        for cls in file_info.classes:
            cls_flows: Dict[str, List[Dict[str, Any]]] = {}
            for method in sorted(cls.methods, key=lambda m: m.name):
                for dec in method.decorator_details:
                    dec_name = dec.get("name", "")
                    if not dec_name or dec_name in _NOISE_DECORATORS:
                        continue
                    if not (dec.get("args") or dec.get("kwargs")):
                        continue
                    entry: Dict[str, Any] = {
                        "function": method.name,
                        "signature": method.signature,
                    }
                    entry.update(dec.get("kwargs", {}))
                    if dec.get("args"):
                        entry["args"] = dec["args"]
                    if dec_name not in cls_flows:
                        cls_flows[dec_name] = []
                    cls_flows[dec_name].append(entry)

            # Sort by 'order' key if present
            for dec_name, entries in cls_flows.items():
                if all("order" in e for e in entries):
                    cls_flows[dec_name] = sorted(entries, key=lambda e: e["order"])

            if cls_flows:
                file_flows[cls.name] = cls_flows

        # Module-level functions
        mod_flows: Dict[str, List[Dict[str, Any]]] = {}
        for func in file_info.functions:
            for dec in func.decorator_details:
                dec_name = dec.get("name", "")
                if not dec_name or dec_name in _NOISE_DECORATORS:
                    continue
                if not (dec.get("args") or dec.get("kwargs")):
                    continue
                entry = {
                    "function": func.name,
                    "signature": func.signature,
                }
                entry.update(dec.get("kwargs", {}))
                if dec.get("args"):
                    entry["args"] = dec["args"]
                if dec_name not in mod_flows:
                    mod_flows[dec_name] = []
                mod_flows[dec_name].append(entry)

        if mod_flows:
            file_flows["(module-level)"] = mod_flows

        if file_flows:
            try:
                rel = str(file_info.path.relative_to(project_root))
            except ValueError:
                rel = str(file_info.path)
            result[rel] = file_flows

    return result


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _regex_to_openapi_path(pattern: str) -> str:
    """
    Convert a Django URL regex to an OpenAPI path string.

    Examples:
        r'^webhooks/(?P<gateway_provider>\\w+)/$'  →  /webhooks/{gateway_provider}/
        r'initiate_gateway_payment/$'              →  /initiate_gateway_payment/
        'users/<int:pk>/'                          →  /users/{pk}/
    """
    # Strip raw string r prefix and outer quotes (already evaluated by _eval_str)
    p = pattern.lstrip("^").rstrip("$")
    # Remove trailing optional slash \/?
    p = re.sub(r"\\/\?$", "/", p)
    # Named regex groups: (?P<name>...)  →  {name}
    p = re.sub(r"\(\?P<(\w+)>[^)]+\)", r"{\1}", p)
    # Django path converters: <int:pk>  →  {pk}
    p = re.sub(r"<(?:\w+:)?(\w+)>", r"{\1}", p)
    # Remove remaining regex special chars, but keep { and } (OpenAPI path params)
    p = re.sub(r"[\\^$*+?|()\[\]]", "", p)
    # Ensure leading /
    if not p.startswith("/"):
        p = "/" + p
    # Normalise double slashes
    p = re.sub(r"//+", "/", p)
    return p


def _call_func_name(node: ast.Call) -> str:
    """Return the function name of a Call node (simple name or attribute)."""
    func = node.func
    if isinstance(func, ast.Name):
        return func.id
    if isinstance(func, ast.Attribute):
        return func.attr
    return ""


def _eval_str(node: ast.expr) -> Optional[str]:
    """Return the string value of a Constant or JoinedStr node, else None."""
    if isinstance(node, ast.Constant) and isinstance(node.value, str):
        return node.value
    # Python 3.7 Str node
    if hasattr(ast, "Str") and isinstance(node, ast.Str):  # type: ignore[attr-defined]
        return node.s  # type: ignore[attr-defined]
    return None


def _extract_view_class_name(node: ast.expr) -> Optional[str]:
    """
    Extract the class name from a `ViewClass.as_view()` call or a plain name.

    Handles:
    - `SomeView.as_view()`              →  "SomeView"
    - `SomeView.as_view(extra_args=...)` →  "SomeView"
    - `SomeView`                         →  "SomeView"
    """
    if isinstance(node, ast.Call):
        func = node.func
        if isinstance(func, ast.Attribute) and func.attr == "as_view":
            if isinstance(func.value, ast.Name):
                return func.value.id
            if isinstance(func.value, ast.Attribute):
                return func.value.attr
    if isinstance(node, ast.Name):
        return node.id
    return None


def _find_class_variable(cls: ClassInfo, var_name: str) -> Optional[str]:
    """
    Return the string value assigned to a class variable like serializer_class.

    Scans the class source code for `var_name = SomeClass` assignments.
    """
    if not cls.code:
        return None
    try:
        tree = ast.parse(cls.code)
    except SyntaxError:
        return None
    for node in ast.walk(tree):
        if not isinstance(node, ast.Assign):
            continue
        for target in node.targets:
            if isinstance(target, ast.Name) and target.id == var_name:
                if isinstance(node.value, ast.Name):
                    return node.value.id
                if isinstance(node.value, ast.Attribute):
                    return node.value.attr
    return None


def _make_operation_id(http_method: str, view_class: str, url_name: Optional[str]) -> str:
    """Generate a unique, readable operationId."""
    base = url_name or view_class
    # Sanitise to identifier-safe string
    base = re.sub(r"[^A-Za-z0-9_]", "_", base)
    return f"{http_method}_{base}"
